# Installs memcached

- name: Install memcached
  apt:
    name: memcached
    state: present
    update_cache: yes
  tags:
    - install
    - install:memcache

- name: Configure it to listen on all interfaces
  lineinfile:
    dest: /etc/memcached.conf
    regexp: '^-l\s+127\.0\.0\.1$'
    line: '-l 0.0.0.0'
    state: present

- name: restart memcache
  service:
    name: memcached
    state: restarted
    enabled: yes
